export const DUMMY_SERVERS = [
  {
    name: 'UT2004 Server',
    map: 'DM-Rankin',
    password: false,
    raw: {
      serverid: 0,
      ip: '',
      queryport: 0,
      gametype: 'xDeathMatch',
      mutators: ['DMMutator'],
      rules: {
        ServerMode: 'dedicated',
        AdminName: 'admin',
        AdminEmail: '',
        ServerVersion: '3369',
        GameStats: 'False',
        MaxSpectators: '2',
        MinPlayers: '0',
        EndTimeDelay: '4.00',
        GoalScore: '25',
        TimeLimit: '20',
        Translocator: 'False',
        WeaponStay: 'True',
        ForceRespawn: 'False',
      },
      ping: 0,
      flags: 0,
      skill: '0',
      scoreboard: {},
    },
    version: '',
    maxplayers: 16,
    numplayers: 1,
    players: [
      { name: 'Eye', raw: { id: 19, ping: 28, score: 0, statsId: 0 } }
    ],
    bots: [],
    queryPort: 7783,
    connect: '192.168.2.14:7782',
    ping: 17,
  },
  {
    name: 'UT TOERNAMENT',
    map: 'CTF-Face',
    password: false,
    raw: {
      gamename: 'ut',
      gamever: 469,
      gamerevision: 'd - Release',
      minnetver: 432,
      location: 0,
      hostname: 'Unreal Tournament',
      hostport: 7777,
      maptitle: 'Facing Worlds',
      mapname: 'CTF-Face',
      gametype: 'CTFGame',
      numplayers: 0,
      maxplayers: 10,
      gamemode: 'openplaying',
      worldlog: true,
      wantworldlog: true,
      mutators: 'InstaGib',
      listenserver: false,
      password: false,
      timelimit: 0,
      goalteamscore: 3,
      minplayers: 4,
      changelevels: true,
      maxteams: 2,
      balanceteams: true,
      playersbalanceteams: true,
      friendlyfire: '0%',
      tournament: 'False',
      gamestyle: 'Hardcore',
      botskill: 'Average',
      adminname: 'UTAdmin',
      adminemail: 'no@one.com',
      teams: {},
    },
    version: 469,
    maxplayers: 10,
    numplayers: 0,
    players: [],
    bots: [],
    queryPort: 7778,
    connect: '192.168.2.14:7777',
    ping: 49,
  },
  {
    name: 'UT2004 Server',
    map: 'DM-Rankin',
    password: false,
    raw: {
      serverid: 0,
      ip: '',
      queryport: 0,
      gametype: 'xDeathMatch',
      mutators: ['DMMutator'],
      rules: {
        ServerMode: 'dedicated',
        AdminName: 'admin',
        AdminEmail: '',
        ServerVersion: '3369',
        GameStats: 'False',
        MaxSpectators: '2',
        MinPlayers: '0',
        EndTimeDelay: '4.00',
        GoalScore: '25',
        TimeLimit: '20',
        Translocator: 'False',
        WeaponStay: 'True',
        ForceRespawn: 'False',
      },
      ping: 0,
      flags: 0,
      skill: '0',
      scoreboard: {},
    },
    version: '',
    maxplayers: 16,
    numplayers: 5,
    players: [
      { name: 'Pook', raw: { ping: 50, score: 10 } },
      { name: 'Eyeliq', raw: { ping: 45, score: 20 } },
      { name: 'Bubba1', raw: { ping: 60, score: 30 } },
      { name: 'Bubba2', raw: { ping: 55, score: 40 } },
      { name: 'Bubba3', raw: { ping: 48, score: 50 } },
    ],
    bots: [],
    queryPort: 7783,
    connect: '192.168.2.14:7782',
    ping: 27,
  },
  {
    name: 'A Minecraft Server',
    map: '',
    password: false,
    raw: {
      vanilla: {
        name: '',
        map: '',
        password: false,
        raw: {
          version: {
            name: '1.20.2',
            protocol: 764,
          },
          description: {
            text: 'A Minecraft Server',
          },
          players: {
            max: 50,
            online: 0,
          },
          bcc: {},
        },
        version: '',
        maxplayers: 50,
        numplayers: 0,
        players: [],
        bots: [],
        queryPort: 25565,
        connect: '192.168.2.14:25565',
        ping: 11,
      },
    },
    version: '1.20.2',
    maxplayers: 50,
    numplayers: 0,
    players: [],
    bots: [],
    queryPort: 25565,
    connect: '192.168.2.14:25565',
    ping: 11,
  },
  {
    name: 'Quake 3',
    map: 'q3dm17',
    password: '0',
    raw: {
      sv_punkbuster: '0',
      sv_floodProtect: '1',
      sv_maxPing: '0',
      sv_minPing: '0',
      sv_maxRate: '0',
      sv_hostname: 'noname',
      version: 'Q3 1.32c linux-i386 May  8 2006',
      dmflags: '0',
      fraglimit: '20',
      timelimit: '0',
      g_gametype: '0',
      protocol: '68',
      mapname: 'q3dm17',
      sv_privateClients: '0',
      sv_maxclients: '8',
      sv_allowDownload: '0',
      bot_minplayers: '0',
      gamename: 'baseq3',
      g_maxGameClients: '0',
      capturelimit: '8',
      g_needpass: '0',
    },
    version: 'Q3 1.32c linux-i386 May  8 2006',
    maxplayers: '8',
    numplayers: 8,
    players: [
      { name: 'Pook', raw: { ping: 50, score: 10 } },
      { name: 'Eyeliq', raw: { ping: 45, score: 20 } },
      { name: 'Bubba1', raw: { ping: 60, score: 30 } },
      { name: 'Bubba2', raw: { ping: 55, score: 40 } },
      { name: 'Bubba3', raw: { ping: 48, score: 50 } },
      { name: 'Bubba4', raw: { ping: 52, score: 60 } },
      { name: 'Bubba5', raw: { ping: 47, score: 70 } },
      { name: 'Bubba6', raw: { ping: 51, score: 80 } },
    ],
    bots: [],
    queryPort: 27960,
    connect: '192.168.2.14:27960',
    ping: 1,
  },
  {
    name: 'Oldskool POEP DM',
    map: 'undertow',
    password: false,
    raw: {
      protocol: 48,
      folder: 'valve',
      game: 'Half-Life',
      appId: 90,
      numbots: 0,
      listentype: 'd',
      environment: 'l',
      secure: 0,
      steamid: '90203789607455744',
      tags: [''],
      players: [],
    },
    version: '1.1.2.2/Stdio',
    maxplayers: 30,
    numplayers: 0,
    players: [],
    bots: [],
    queryPort: 26901,
    connect: '192.168.2.14:26901',
    ping: 7,
  },
  {
    name: 'GoldenEye: Source',
    map: 'ge_bunker',
    password: false,
    raw: {
      protocol: 17,
      folder: 'gesource',
      game: 'Arsenal',
      appId: 218,
      numbots: 0,
      listentype: 'd',
      environment: 'l',
      secure: 0,
      steamid: '90071992547409920',
      tags: ['alltalk', 'autoteamplay', 'increased_maxplayers'],
      players: [],
    },
    version: '1.0.1.0',
    maxplayers: 20,
    numplayers: 0,
    players: [],
    bots: [],
    queryPort: 26900,
    connect: '192.168.2.14:26900',
    ping: 11,
  },
  {
    name: 'poep coop',
    map: 'BlackMesaEPF',
    password: false,
    raw: {
      protocol: 17,
      folder: 'svencoop',
      game: 'Sven Co-op 5.25',
      appId: 225840,
      numbots: 0,
      listentype: 'd',
      environment: 'l',
      secure: 0,
      steamid: '90071992547409920',
      tags: [''],
      players: [],
    },
    version: '5.0.1.7',
    maxplayers: 30,
    numplayers: 0,
    players: [],
    bots: [],
    queryPort: 27015,
    connect: '192.168.2.14:27015',
    ping: 8,
  },
  {
    name: 'Half Life 2',
    map: 'dm_lockdown',
    password: false,
    raw: {
      protocol: 17,
      folder: 'hl2mp',
      game: 'Half-Life 2 Deathmatch',
      appId: 320,
      numbots: 0,
      listentype: 'd',
      environment: 'l',
      secure: 0,
      steamid: '90071992547409920',
      tags: ['"increased_maxplayers', 'alltalk', 'alltalk"', 'increased_maxplayers'],
      players: [],
    },
    version: '6630498',
    maxplayers: 16,
    numplayers: 0,
    players: [],
    bots: [],
    queryPort: 26902,
    connect: '192.168.2.14:26902',
    ping: 11,
  },
  {
    name: 'HalfLife DM source',
    map: 'crossfire',
    password: false,
    raw: {
      protocol: 17,
      folder: 'hl1mp',
      game: 'Half-Life 1',
      appId: 360,
      numbots: 0,
      listentype: 'd',
      environment: 'l',
      secure: 1,
      steamid: '90203789607867392',
      tags: ['increased_maxplayers', 'alltalk', 'gravity', '"increased_maxplayers', 'alltalk"'],
      players: [],
    },
    version: '6630498',
    maxplayers: 30,
    numplayers: 3,
    players: [],
    bots: [],
    queryPort: 26903,
    connect: '192.168.2.14:26903',
    ping: 9,
  },
  {
    name: 'Alien Swarm Reactive Drop',
    map: 'ASI-Jac1-LandingBay_01',
    password: false,
    raw: {
      protocol: 17,
      folder: 'reactivedrop',
      game: 'Alien Swarm: Reactive Drop',
      appId: 563560,
      numbots: 0,
      listentype: 'l',
      environment: 'l',
      secure: 1,
      steamid: '90203789607664640',
      tags: ['Normal', 'Briefing', 'empty'],
      players: [],
    },
    version: '7.1.4.5',
    maxplayers: 8,
    numplayers: 2,
    players: [
      { name: 'Pook', raw: { ping: 35, score: 10 } },
      { name: 'Eyeliq', raw: { ping: 42, score: 20 } },
    ],
    bots: [],
    queryPort: 27018,
    connect: '192.168.2.14:27018',
    ping: 0,
  },
  {
    name: 'Valheimpie',
    map: 'Valheim',
    password: false,
    raw: {},
    version: '',
    maxplayers: 10,
    numplayers: 0,
    players: [],
    bots: [],
    queryPort: 24567,
    connect: '192.168.2.14:24567',
    ping: 11,
  },
  {
    name: 'G4N BAR o Trauma',
    map: 'Valheim',
    password: false,
    raw: {},
    version: '',
    maxplayers: 10,
    numplayers: 0,
    players: [],
    bots: [],
    queryPort: 24567,
    connect: '192.168.2.14:24567',
    ping: 13,
  },
];

// Example payload
// {
//   "name": "UT2004 Server",
//   "map": "DM-Rankin",
//   "password": false,
//   "raw": {
//     "serverid": 0,
//     "ip": "",
//     "queryport": 0,
//     "gametype": "xDeathMatch",
//     "mutators": [
//       "DMMutator"
//     ],
//     "rules": {
//       "ServerMode": "dedicated",
//       "AdminName": "admin",
//       "AdminEmail": "",
//       "ServerVersion": "3369",
//       "GameStats": "False",
//       "MaxSpectators": "2",
//       "MinPlayers": "0",
//       "EndTimeDelay": "4.00",
//       "GoalScore": "25",
//       "TimeLimit": "20",
//       "Translocator": "False",
//       "WeaponStay": "True",
//       "ForceRespawn": "False"
//     },
//     "ping": 0,
//     "flags": 0,
//     "skill": "0",
//     "scoreboard": {}
//   },
//   "version": "",
//   "maxplayers": 16,
//   "numplayers": 1,
//   "players": [
//     {
//       "name": "Eye",
//       "raw": {
//         "id": 19,
//         "ping": 28,
//         "score": 0,
//         "statsId": 0
//       }
//     }
//   ],
//   "bots": [],
//   "queryPort": 7783,
//   "connect": "192.168.2.14:7782",
//   "ping": 17
// }